cms_pageeng:
    path:     /
    defaults: { _controller: "mehunEngContentBundle:PageEng:index" }

cms_pageeng_show:
    path:     /{id}/show
    defaults: { _controller: "mehunEngContentBundle:PageEng:show" }

cms_pageeng_new:
    path:     /new
    defaults: { _controller: "mehunEngContentBundle:PageEng:new" }

cms_pageeng_create:
    path:     /create
    defaults: { _controller: "mehunEngContentBundle:PageEng:create" }
    methods:  POST

cms_pageeng_edit:
    path:     /{id}/edit
    defaults: { _controller: "mehunEngContentBundle:PageEng:edit" }

cms_pageeng_update:
    path:     /{id}/update
    defaults: { _controller: "mehunEngContentBundle:PageEng:update" }
    methods:  [POST, PUT]

cms_pageeng_delete:
    path:     /{id}/delete
    defaults: { _controller: "mehunEngContentBundle:PageEng:delete" }
    methods:  [POST, DELETE]
