cms_page:
    path:     /
    defaults: { _controller: "mehunContentBundle:Page:index" }

cms_page_show:
    path:     /{id}/show
    defaults: { _controller: "mehunContentBundle:Page:show" }

cms_page_new:
    path:     /new
    defaults: { _controller: "mehunContentBundle:Page:new" }

cms_page_create:
    path:     /create
    defaults: { _controller: "mehunContentBundle:Page:create" }
    methods:  POST

cms_page_edit:
    path:     /{id}/edit
    defaults: { _controller: "mehunContentBundle:Page:edit" }

cms_page_update:
    path:     /{id}/update
    defaults: { _controller: "mehunContentBundle:Page:update" }
    methods:  [POST, PUT]

cms_page_delete:
    path:     /{id}/delete
    defaults: { _controller: "mehunContentBundle:Page:delete" }
    methods:  [POST, DELETE]
