cms_user:
    path:     /
    defaults: { _controller: "mehunContentBundle:User:index" }

cms_user_show:
    path:     /{id}/show
    defaults: { _controller: "mehunContentBundle:User:show" }

cms_user_new:
    path:     /new
    defaults: { _controller: "mehunContentBundle:User:new" }

cms_user_create:
    path:     /create
    defaults: { _controller: "mehunContentBundle:User:create" }
    methods:  POST

cms_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "mehunContentBundle:User:edit" }

cms_user_update:
    path:     /{id}/update
    defaults: { _controller: "mehunContentBundle:User:update" }
    methods:  [POST, PUT]

cms_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "mehunContentBundle:User:delete" }
    methods:  [POST, DELETE]
